wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1658488422
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 24
      4: 3.7.11
      5: 0.12.21
      8:
      - 5
dataset:
  desc: null
  value: HeteroData
dropout:
  desc: null
  value: 0.3
embedding_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 60
lr:
  desc: null
  value: 0.005
model_name:
  desc: null
  value: TweetAugmentedHAN2ExtraLayer
svdComponents:
  desc: null
  value: 200
thirds:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.005
