wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1658058188
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      4: 3.7.11
      5: 0.12.21
      8:
      - 5
dataset:
  desc: null
  value: HeteroData
dropout:
  desc: null
  value: 0.3
embedding_size:
  desc: null
  value: 96
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.001
model_name:
  desc: null
  value: TweetAugmentedHAN
svdComponents:
  desc: null
  value: 100
thirds:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.005
